name: Deploy to WP Engine
on:
  push:
    branches:
     production:
     - step:
         script:          
            - echo 'bitbucket-pipelines.yml' >> .gitignore            
            - git push --force git@git.wpengine.com:production/sccpractice.git
            - echo "Pushed to Production"
jobs:
  build:
    runs-on: ubuntu-latest  
    steps: 
    - uses: actions/checkout@v2
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3.0
      with:
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        WPE_ENV: <your_install_name_here>